blank_issues_enabled: true
contact_links:
  - name: New Feature
    about: 新機能の提案はこちら
    url: https://github.com/RQC-HU/dirac_caspt2/issues/new?template=feature_request.md&projects=RQC-HU/dirac_caspt2/1&labels=enhancement
  - name: Bug Report
    about: バグレポートはこちら
    url: https://github.com/RQC-HU/dirac_caspt2/issues/new?template=bug-report.md&projects=RQC-HU/dirac_caspt2/1&labels=bug
  - name: Blank Issue
    about: new Issue with no template file
    url: https://github.com/RQC-HU/dirac_caspt2/issues/new?projects=RQC-HU/dirac_caspt2/1
