! +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
! +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

SUBROUTINE print_head

! +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
! +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=

    use module_global_variables, only: rank

    Implicit NONE

    if (rank == 0) then
        print *, ''
        print '(84A)', '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'
        print '(84A)', '@        ____  _____ _        _  _____ _____     _____ ____ _____ ___ ____         @'
        print '(84A)', '@       |  _ \| ____| |      / \|_   _|_ _\ \   / /_ _/ ___|_   _|_ _/ ___|        @'
        print '(84A)', '@       | |_) |  _| | |     / _ \ | |  | | \ \ / / | |\___ \ | |  | | |            @'
        print '(84A)', '@       |  _ <| |___| |___ / ___ \| |  | |  \ V /  | | ___) || |  | | |___         @'
        print '(84A)', '@       |_|_\_\_____|_____/_/___\_\_|_|___|_ \_/  |___|____/ |_| |___\____|        @'
        print '(84A)', '@                       / ___|  / \  / ___||  _ \_   _|___ \                       @'
        print '(84A)', '@                      | |     / _ \ \___ \| |_) || |   __) |                      @'
        print '(84A)', '@                      | |___ / ___ \ ___) |  __/ | |  / __/                       @'
        print '(84A)', '@                       \____/_/   \_\____/|_|    |_| |_____|                      @'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@       Developped by Kohei Noda, Yasuto Masuda, Sumika Iwamuro, Minori Abe        @'
        print '(84A)', '@               Hiroshima University & Tokyo Metropolitan Univeristy               @'
        print '(84A)', '@                     https://github.com/RQC-HU/dirac_caspt2                       @'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@                MMMN,                                    .MMp                     @'
        print '(84A)', '@               .#  ?YMa,                                dM\Tb                     @'
        print '(84A)', '@               .F    ,MMm,                             dM#  .W,                   @'
        print '(84A)', '@               (F      TMMp                           JMMt    7,                  @'
        print '(84A)', '@               J]       4MMp                      .dMM@       M[                  @'
        print '(84A)', '@               M\        ?MMh.                    .(MMMF       -N.                @'
        print '(84A)', '@              .M          qMMMN+.............(+gMMMMM@^ (((()  MN                 @'
        print '(84A)', '@              (F          .MT"^ _~?77?!~~???77"^ ``,!           JM!               @'
        print '(84A)', '@              M]                                                  TN,             @'
        print '(84A)', '@             .M}                                                  VMp             @'
        print '(84A)', '@             MM        .gMMMNJ.                 ..MMMMMa,          UM2            @'
        print '(84A)', '@            JP       .MMMMMMMMMN,              .M^MMMMN,TN,         UMp           @'
        print '(84A)', '@           Jb        M@.MMMMMM)?Mh           .M^ MMMMMM] ?h          MMb          @'
        print '(84A)', '@          .M^       .Hp 4MMMM!  .Mb          .M  (MMMM) ..9]      ...(MMNCASPT2   @'
        print '(84A)', '@         .Mh.(J.,     TMNMMMMNM"^ 7`         TWgJuMMNg&M"     .d"""777MM!~??`     @'
        print '(84A)', '@    ..gMMMM"^ .^          ?^                       ^^?                q@]         @'
        print '(84A)', '@  .MM#"` MF        ^^^               ......             ^^^           -b          @'
        print '(84A)', '@ , "     HN{                         WMMMM\   ..&,.           MNMNH96jM@          @'
        print '(84A)', '@         .Mh,                 .       /M@^        //              _7^WMMMMNg,.    @'
        print '(84A)', '@          dMugNMMMMMM9         .%      M:       ..M`                J@    74,     @'
        print '(84A)', '@        ..MMM&       ..        TMa....M9WNmQggN#^?          jQNgg+..MF            @'
        print '(84A)', '@      .M@^ .dMMo..gd ^`            `                          ?jM RASPT2.         @'
        print '(84A)', '@     dF      ~jMM#1.               .N,      .N=        `   ..g#      .7           @'
        print '(84A)', '@             .MMTTMMNm,.            -MMMWyM9-         ..+MMMT=)  dMM      mi      @'
        print '(84A)', '@           .dMF    7?W""9g...,                 ...J"=`y"D`         FFM            @'
        print '(84A)', '@          .MMF                 ^    """"""""   ^                      KK.         @'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@       This program is intended to be used after HF and MO transformation         @'
        print '(84A)', '@       calculations uisng the DIRAC software.                                     @'
        print '(84A)', '@       https://www.diracprogram.org/doku.php?id=start                             @'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@       You can use, redistribute and/or modify this program under the terms       @'
        print '(84A)', '@       of the GNU Lesser General Public License version 2.1 as published          @'
        print '(84A)', '@       by the Free Software Foundation.                                           @'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@       Please cite the following paper when you publish the data obtained         @'
        print '(84A)', '@       using this program.                                                        @'
        print '(84A)', '@       1. Y. Masuda, K. Noda, S. Iwamuro, M. Hada, N. Nakatani, M. Abe.           @'
        print '(84A)', '@          Relativistic CASPT2/RASPT2 Program along with DIRAC software.           @'
        print '(84A)', '@          J. Chem. Theory Comput. 2025, 21, 3, 1249–1258;                         @'
        print '(84A)', '@          https://doi.org/10.1021/acs.jctc.4c01589                                @'
        print '(84A)', '@       2. M. Abe, T. Nakajima, K. Hirao.                                          @'
        print '(84A)', '@          The relativistic complete active-space second-order                     @'
        print '(84A)', '@          perturbation theory with the four-component Dirac Hamiltonian           @'
        print '(84A)', '@          J. Chem. Phys. 2006, 125, 234110;                                       @'
        print '(84A)', '@          https://doi.org/10.1063/1.2404666                                       @'
        print '(84A)', '@       3. K. Andersson, P. A. Malmqvist, B. O. Roos, A. J. Sadlej, K. Wolinski.   @'
        print '(84A)', '@          Second-order perturbation theory with a CASSCF reference function       @'
        print '(84A)', '@          J. Phys. Chem. 1990, 94, 14, 5483–5488;                                 @'
        print '(84A)', '@          https://doi.org/10.1021/j100377a012                                     @'
        print '(84A)', '@       4. S. Huzinaga, and C. Arnau                                               @'
        print '(84A)', '@          Virtual Orbitals in Hartree-Fock Theory.                                @'
        print '(84A)', '@          Phys. Rev. A. 1970, 1, 1285-1288;                                       @'
        print '(84A)', '@          https://doi.org/10.1103/PhysRevA.1.1285                                 @'
        print '(84A)', '@       We do not take any responsibility for the results produced                 @'
        print '(84A)', '@       by this program.                                                           @'
        print '(84A)', '@                                                                                  @'
        print '(84A)', '@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@'
        print *, ''
    end if

end subroutine print_head
